apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharmacymedicinesupplyservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PharmacyMedicineSupplyService
  template:
    metadata:
      labels:
        app: PharmacyMedicineSupplyService
    spec:
      containers:
      - name: pharmacymedicinesupplyrepos
        image:medicinesupplycr.azurecr.io/pharmacymedicinesupplyrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: pmsmsecret

---
apiVersion: v1
kind: Service
metadata:
  name: pharmacymedicinesupplyservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: PharmacyMedicineSupplyService
